services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: accommodation_rental
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - "2345:5432"
  backend:
    image: gorazdbiskoski/accommodations_backend:latest
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accommodation_rental
      SPRING_DATASOURCE_USERNAME: emt
      SPRING_DATASOURCE_PASSWORD: emt
  web:
    image: gorazdbiskoski/accommodations_frontend:latest
    depends_on:
      - db
      - backend
    restart: always
    ports:
      - "3000:3000"

volumes:
  pgdata:
