CREATE TABLE country (
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    continent       varchar(255)
);

CREATE TABLE host (
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    surname         varchar(255),
    country_id      bigint references country on delete cascade
);

CREATE TABLE accommodation (
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    category        varchar(50),
    host_id         bigint references host on delete cascade ,
    num_rooms       integer,
    is_available    boolean
);

CREATE TABLE users (
    id                              bigint generated by default as identity primary key,
    username                        varchar(255),
    password                        varchar(255),
    name                            varchar(255),
    role                            varchar(50),
    is_account_non_expired          boolean default true,
    is_account_non_locked           boolean default true,
    is_credentials_non_expired      boolean default true,
    is_enabled                      boolean default true
);

CREATE TABLE users_reservations (
    user_id bigint references users on delete cascade,
    reservations_id bigint references accommodation on delete cascade,
    primary key (user_id, reservations_id)
);