name: Build and Push Frontend Docker Image

on:
  push:
    paths:
      - 'accommodation-rental-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./accommodation-rental-frontend
          file: ./accommodation-rental-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/accommodations_frontend:latest
